version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_poo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    ports:
      - "6000:6000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@db:5432/db_poo  # URI ajustado para conectarse al contenedor de la DB
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
